name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: chmod +x install.sh && source ./install.sh my-image-name:$(date +"%m-%d-%Y") && docker save my-image-name:$(date +"%m-%d-%Y") > result.tar
    - name: Zip artifact for deployment
      run: zip release.zip result.tar
